spring:
  datasource:
    url: jdbc:mysql://blog.wmgx.top:3306/psychological
    username: psychological
    password: psychological

mybatis-plus:
  typeHandlersPackage: com.nh.micro.ext.th


  global-config:
    db-config:
      id-type: auto


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
