spring:
  datasource:
    url: jdbc:mysql://blog.wmgx.top:3306/psychological
    username: psychological
    password: psychological


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: true
      logic-not-delete-value: false
      id-type: assign_id

  typeHandlersPackage: com.nh.micro.ext.th


  configuration:
    log-impl: top.wmgx.MybatisLogPlus
server:
  port: 8081
